CREATE TABLE CAT_BREED(
  ID INT    PRIMARY KEY NOT NULL,
  BREED_CODE TEXT       NOT NULL,
  BREED TEXT            NOT NULL,
  BREED_DESC TEXT
);

CREATE TABLE DOG_BREED (
  ID INT PRIMARY KEY NOT NULL,
  BREED_CODE TEXT NOT NULL,
  BREED TEXT NOT NULL,
  BREED_DESC TEXT
)



